version: '3.8'

services:
  app: 
    build: .
    ports:
      - 3000:3000
    restart: always
    volumes:
      - .:/app
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - db
  db: 
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
