import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased crt relative w-full h-full h-screen font-mono`}
      >
        <div className="scanlines"></div>
      {children}
      </body>
    </html>
  );
}
