name: ci/cd

on: 
  push:
    branches: [main]

jobs:
  lintTest: 
    name: Lint & Test
    runs-on: ubuntu-latest
    steps: 
      - name: Setup Bun
        run: |
          echo "Installing Bun..."
          curl -fsSL https://bun.sh/install | bash

      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          echo "Installing Dependencies..."
          bun install

      - name: Lint
        run: |
          echo "Linting..."
          bun lint