name: ci/cd

on: 
  push:
    branches: [main]
jobs:
  build:
    name: Build and push to Docker Hub
    needs: lintTest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: 07CalC
          password: ${{ secrets.GHRC_PASSWORD }}
      - name: Build and push docker image
        id: build-and-push-image
        run: |
          ls -la
          docker build -t ghcr.io/07calc/crux:latest .
          docker push ghcr.io/07calc/crux:latest

